### ISSUE TITLE
BEEFY client milestone: prod network ready

### ISSUE THREAD

**Issue by acatangiu** [paritytech/parity-bridges-common#1634]
# The Vision

Have the BEEFY-client/BEEFY-voter functioning correctly and reliably in all network conditions and scenarios, with no trust or assumptions of fairness from other nodes/voters/validators.

This means implementing and relying on economic (dis)incentivization mechanisms.

# The Plan

- [ ] https://github.com/paritytech/substrate/issues/12692
- [ ] https://github.com/paritytech/substrate/issues/12293
- [ ] https://github.com/paritytech/substrate/issues/12294
