### ISSUE TITLE
MMR milestone: production ready Merkle Mountain Range pallet (and gadget)

### ISSUE THREAD

**Issue by acatangiu** [paritytech/parity-bridges-common#1636]
# The Vision

Have an on-chain MMR capable of following chain progress and capable of proving some _customizable leaf data_ is part of the chain.

## Requirements
- Minimal on-chain data,
- Full MMR contents should go to offchain db and should be optional for nodes,
- Any node can verify proofs,
- Generating proofs can be done only by nodes that opted in saving full MMR offchain.

# The Plan

- [x] https://github.com/paritytech/grandpa-bridge-gadget/issues/336
- [x] https://github.com/paritytech/substrate/issues/11984
- [x] https://github.com/paritytech/substrate/issues/11753
- [x] https://github.com/paritytech/substrate/issues/12339
- [x] ~https://github.com/paritytech/substrate/issues/11799~  <-- (attempts to do it failed, dropping it)
- [x] https://github.com/paritytech/substrate/issues/11972
- [x] https://github.com/paritytech/substrate/issues/12508
- [x] https://github.com/paritytech/substrate/issues/12531
- [x] https://github.com/paritytech/substrate/issues/12780
- [x] https://github.com/paritytech/substrate/issues/12804
- [x] https://github.com/paritytech/substrate/issues/11797
- [x] https://github.com/paritytech/substrate/issues/12864

## Integration

- [x] Deploy and test all the above on Rococo
