### ISSUE TITLE
[R-W Bridge] Relayer economics

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#1702]
Integrating rewards, batch transactions, delivery confirmations, signed extensions for refund and partial relayer payment.

## Work Breakdown

- [x] https://github.com/paritytech/parity-bridges-common/pull/1652
- [x] https://github.com/paritytech/parity-bridges-common/pull/1653
- [x] https://github.com/paritytech/parity-bridges-common/pull/1657
- [x] https://github.com/paritytech/parity-bridges-common/pull/1669
- [x] https://github.com/paritytech/parity-bridges-common/issues/1648
- [ ] https://github.com/paritytech/parity-bridges-common/issues/1677
- [x] https://github.com/paritytech/parity-bridges-common/issues/1640

**Comment by acatangiu** [comment]
I say for R<>W we can close this issue as done. We will get the full relayer economics picture when we look at P<>K bridge and also take into account all security audit feedback.
