### ISSUE TITLE
BridgeHub initial set-up and deployment

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#1703]
## Work Breakdown

- [x] https://github.com/paritytech/parity-bridges-common/pull/1701
- [x] https://github.com/paritytech/parity-bridges-common/issues/1627
- [x] https://github.com/paritytech/parity-bridges-common/issues/1551
- [x] https://github.com/paritytech/parity-bridges-common/issues/1401
- [x] https://github.com/paritytech/parity-bridges-common/issues/1162
- [x] https://github.com/paritytech/parity-bridges-common/issues/1673
