### ISSUE TITLE
Rococo - Wococo Bridge Checkpoint #1

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#1704]
## Work Breakdown 

- [x] https://github.com/paritytech/parity-bridges-common/issues/1676
- [x] https://github.com/paritytech/parity-bridges-common/issues/1675
- [x] https://github.com/paritytech/parity-bridges-common/issues/1678
- [x] https://github.com/paritytech/parity-bridges-common/issues/1680

**Comment by bkontur** [comment]
@EmmanuellNorbertTulbure 
we could close this now also

**Comment by acatangiu** [comment]
This is done :smiley:
