### ISSUE TITLE
Rococo <> Wococo Assets Transfer

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#1705]
## Work Breakdown

- [x] https://github.com/paritytech/parity-bridges-common/issues/1681
- [x] https://github.com/paritytech/parity-bridges-common/issues/1682
- [x] https://github.com/paritytech/parity-bridges-common/issues/1683
- [x] https://github.com/paritytech/parity-bridges-common/issues/1684
- [x] https://github.com/paritytech/parity-bridges-common/issues/1685
- [x] https://github.com/paritytech/parity-bridges-common/issues/1828

**Comment by bkontur** [comment]
I guess, we can close this, 
we have deployed kubernetes cron job which transfers periodically ROC from rockmine2 account to wockmint account

**Comment by bkontur** [comment]
I guess, we can close this, 
we have deployed kubernetes cron job which transfers periodically ROC from rockmine2 account to wockmint account
