### ISSUE TITLE
Rococo <> Wococo BridgeHubs deployment

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#1706]
## Work Breakdown

- [x] https://github.com/paritytech/parity-bridges-common/issues/1638
- [x] https://github.com/paritytech/parity-bridges-common/issues/391
- [x] https://github.com/paritytech/parity-bridges-common/issues/1672
- [x] https://github.com/paritytech/parity-bridges-common/issues/1576
- [x] https://github.com/paritytech/parity-bridges-common/issues/1640
- [x] https://github.com/paritytech/parity-bridges-common/issues/1674
- [x] https://github.com/paritytech/parity-bridges-common/issues/1679
- [x] https://github.com/paritytech/parity-bridges-common/issues/1715
