### ISSUE TITLE
Tracking Issue from Substrate Repo for Sub2Sub bridge components

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#18]
I'm migrating this from the [Substrate repo](paritytech/substrate#3703) for the sake of continuity. I think that these TODOs should be broken up into individual issues at some point, but since the design is still in a bit of flux that can wait.

Original PR TODOs
-----------------------

This PR is going to track the development of #1850. Development will be done on other branches and PR'd into this one. This is being done in order to not have half baked code in Substrate, as well as making it easier for others to review.

Some of the TODOs are:
- [ ] Have a module that can act as a light client for another chain (not necessarily do anything with that data though)
- [ ] Verify GRANDPA finality proofs on-chain
- [ ] Verify block ancestry proofs on-chain
- [ ] Have an RPC for actors to submit claims from other chains
- [ ] Message delivery and acknowledgement infrastructure
- [ ] Default message handler for the receiving end of the bridge

Additionally, a bridge relay node will need to be implemented, which will need to do the following:
- [ ] Relay finalized headers to bridged chains
- [ ] Relay outbound messages to bridged chains
- [ ] Relay message delivery acknowledgements to bridged chains

The bridge relay node issues could probably be tracked in a separate issue as they are fairly independent of the module itself.

**Comment by tomusdrw** [comment]
> I think that these TODOs should be broken up into individual issues at some point, but since the design is still in a bit of flux that can wait.

Yes. Let's create and self-assign to issues in this repo in general (CC @svyatonik @hernando), I very much prefer smaller issues than this kind of meta-issues.

**Comment by tomusdrw** [comment]
Closing in favour of smaller issues that I'm about to open.
