### ISSUE TITLE
[P-K Bridge] AssetHubs - withdraw reserve asset transfer (opposite direction)

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#2256]
simple scenario: **(move back and forth KSM from AssetHubKusama to AssetHubPolkadot)**
- AssetHubKusama does reserve for KSM -> `ReserveAssetDeposited(KSM)` -> AssetHubPolkadot receive pKSM
- way back AssetHubPolkadot burn pKSM-> WithdrawAsset(pKSM) -> AssetHubKusama withdraw reserve of KSM

---
we have two PoC for reserve based tranfer:

1. PoC - with custom extrinsic supports both ways (way back withtout `InitiateReserveWithdraw` instruction)  - https://github.com/paritytech/cumulus/pull/2013
2. PoC - with `pallet_xcm` - https://github.com/paritytech/cumulus/pull/2762
    - supports only `reserve_asset_transfer`
    - `pallet_xcm` does not even support `reserve_withdraw_assets` yet
      - there exists unfinished/unmerged attempt https://github.com/paritytech/polkadot/pull/5975 

---
**TODOs/open questions:**

- [ ] why `pallet_xcm` does not support `InitiateReserveWithdraw` is there a reason for that?
- [ ] what about AssetHubs - do they have to implement their custom logic/extrinsic for `InitiateReserveWithdraw`?
- [ ] what should be a good design for `InitiateReserveWithdraw` and/or are there any caveats?

**Comment by bkontur** [comment]
we are going with adding support for withdraw to `pallet_xcm` - https://github.com/paritytech/polkadot/pull/5975
