### ISSUE TITLE
Governance Calls P<>K Bridge

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#2390]
- [x] **Polkadot governance call** - see [comment](https://github.com/paritytech/parity-bridges-common/issues/2390#issuecomment-1971490775)
  - [x] Init Bridge Pallet
    - [x] Kusama -> Polkadot https://github.com/paritytech/parity-bridges-common/issues/2390#issuecomment-1932064318
  - [x] `forceXcmVersion` governance calls
    - [x] on BridgeHubPolkadot for BridgeHubKusama: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-bridge-hub-rpc.polkadot.io#/extrinsics/decode/0x1f040202090300a90f03000000
    - [x] on AssetHubPolkadot for AssetHubKusama
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x1f040202090300a10f03000000
    - [x] on AssetHubPolkadot for BridgeHubPolkadot:  (just in case, safeXcmVersion is still 2)
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x1f04010100a90f03000000
- [x] **Kusama governance call** - see [comment](https://github.com/paritytech/parity-bridges-common/issues/2390#issuecomment-1971539762)
  - [x] Init Bridge Pallet
    - [x] Polkadot -> Kusama https://github.com/paritytech/parity-bridges-common/issues/2390#issuecomment-1932076584
  - [x] `forceXcmVersion` governance calls
    - [x] on BridgeHubKusama for BridgeHubPolkadot:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-bridge-hub-rpc.polkadot.io#/extrinsics/decode/0x1f040202090200a90f03000000
    - [x] on BridgeHubKusama for AssetHubKusama:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-bridge-hub-rpc.polkadot.io#/extrinsics/decode/0x1f04010100a10f03000000
    - [x] on AssetHubKusama for AssetHubPolkadot:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x1f040202090200a10f03000000
    - [x] on AssetHubKusama for BridgeHubKusama:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x1f04010100a90f03000000
- [x] ~~`forceDefaultXcmVersion(3)` on BridgeHubs~~ https://github.com/polkadot-fellows/runtimes/issues/190
- [ ] Registering Relayers
- [ ] Setting Proper Constant Values (PBH/KBH runtime upgrades)
- [ ] Funding Relayers
  - [ ] TODO: collect all accounts
- [ ] Funding all sovereign accounts
  - [ ] TODO: collect all accounts

**Comment by bkontur** [comment]
- [ ] init bridge Kusama -> Polkadot

1. Generate `initialize` init-bridge call as `hex-encoded-data`:

```
git clone https://github.com/paritytech/parity-bridges-common.git
git checkout -b polkadot-staging --track origin/polkadot-staging
cargo build --release -p substrate-relay

# Kusama -> Polkadot
RUST_LOG=bridge=info \
	./target/release/substrate-relay init-bridge kusama-to-bridge-hub-polkadot \
	--source-host kusama-rpc.polkadot.io \
	--source-port 443 \
	--source-secure \
	--target-host polkadot-bridge-hub-rpc.polkadot.io \
	--target-port 443 \
	--target-secure \
	--target-signer //Bob \
	--dry-run
	
...

2022-12-02 09:08:38 +00 INFO bridge Initialize bridge call encoded as hex string: "TODO: data"
```

encoded call data:
```
TODO: generate actual encoded data
```

2. Check `hex-encoded-data` here: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-bridge-hub-rpc.polkadot.io#/extrinsics/decode

3. Submit governance call as extrinsic with `XCM::Transact` with `hex-encoded-data` for `para_id=1002` from **Polkadot relay node** 

TODO: prepare command/call for `opengov-cli`

**Comment by bkontur** [comment]
- [ ] init bridge Polkadot -> Kusama

1. Generate `initialize` init-bridge call as `hex-encoded-data`:

```
git clone https://github.com/paritytech/parity-bridges-common.git
git checkout -b polkadot-staging --track origin/polkadot-staging
cargo build --release -p substrate-relay

# Polkadot -> Kusama
RUST_LOG=bridge=info \
	./target/release/substrate-relay init-bridge polkadot-to-bridge-hub-kusama \
	--source-host dot-rpc.stakeworld.io \
	--source-port 443 \
	--source-secure \
	--target-host kusama-bridge-hub-rpc.polkadot.io \
	--target-port 443 \
	--target-secure \
	--target-signer //Bob \
	--dry-run	
...

2022-12-02 09:08:38 +00 INFO bridge Initialize bridge call encoded as hex string: "TODO: data"
```

encoded call data:
```
TODO: generate actual encoded data
```

2. Check `hex-encoded-data` here: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-bridge-hub-rpc.polkadot.io#/extrinsics/decode

3. Submit governance call as extrinsic with `XCM::Transact` with `hex-encoded-data` for `para_id=1002` from **Kusama relay node** 

TODO: prepare command/call for `opengov-cli`

**Comment by bkontur** [comment]
@svyatonik just one thing came to my mind, I am not sure about, but if we submit `init-bridge` calls with some data at some point T1, and when governance calls are enacted at other time T2. Do we need to make sure that our relayer is connected to some node which has old data (archive?)? I mean, if can possibly happen that RPC node (maybe not archive mode) does not have `init-bridge` data, because they were pruned from its state or something like that?

**Comment by svyatonik** [comment]
> @svyatonik just one thing came to my mind, I am not sure about, but if we submit `init-bridge` calls with some data at some point T1, and when governance calls are enacted at other time T2. Do we need to make sure that our relayer is connected to some node which has old data (archive?)? I mean, if can possibly happen that RPC node (maybe not archive mode) does not have `init-bridge` data, because they were pruned from its state or something like that?

I'm not sure I understand. Why do we need data for `init-bridge` at `T2`? The `initialize` call data is collected at `T1` and we do not need an archive node for that. Then we hand it to governance and on apply, we do our usual `relay-headers-and-messages` stuff. And for that we don't need an archive node too. So IIUC we won't need an archive node anywhere.

**Comment by bkontur** [comment]
> > @svyatonik just one thing came to my mind, I am not sure about, but if we submit `init-bridge` calls with some data at some point T1, and when governance calls are enacted at other time T2. Do we need to make sure that our relayer is connected to some node which has old data (archive?)? I mean, if can possibly happen that RPC node (maybe not archive mode) does not have `init-bridge` data, because they were pruned from its state or something like that?
> 
> I'm not sure I understand. Why do we need data for `init-bridge` at `T2`? The `initialize` call data is collected at `T1` and we do not need an archive node for that. Then we hand it to governance and on apply, we do our usual `relay-headers-and-messages` stuff. And for that we don't need an archive node too. So IIUC we won't need an archive node anywhere.

Ok, let's just ignore my comment then. It might have been a brainfart on my end. I vaguely recall encountering a situation with BridgeHubRococo where PJS couldn't display some older blocks, but I don't remember exactly what was that about (hopefully not just my imagination or dream :D), maybe it was some issue with local run or whatever :D

**Comment by svyatonik** [comment]
Yes - PJS can't access state (read runtime storage or do runtime calls) at already pruned blocks. But it can access chain data for all blocks since genesis (assuming it is fully synced if warp was used). This chain data includes: block headers, block transactions (headers + transactions = blocks) and justifications. That's what we need to be able to sync our light client (bridge GRANDPA pallet) to the latest state of bridged chain.

So at `T1` we need access to the state to prepare the initialization data (IIRC we read GRANDPA authority set using some runtime calls). But once it is prepared, we won't rely on runtime state of ancient blocks (which may be pruned). Our relayer only access state of recent blocks.

So IIUC everything should be fine :)

**Comment by svyatonik** [comment]
Bridge is live, all gov calls have been successfully submitted
