### ISSUE TITLE
Tracking issue for Polkadot Bulletin Chain <> Polkadot Bridge Hub bridge

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#2547]
All development should happen in master and then backported to the [polkadot-v.1.0.0-audited](https://github.com/paritytech/parity-bridges-common/tree/polkadot-v.1.0.0-audited) branch (and `polkadot-staging` eventually).

Tasks that would allow us to test it locally:
- [x] add Bulletin Chain primitives (#2542);
- [x] add required pallets to Polkadot Bridge Hub (on top of https://github.com/paritytech/polkadot-sdk/pull/1352) (https://github.com/paritytech/polkadot-sdk/tree/sv-bulletin-chain-bridge):
   - [x] make sure that we only register transaction fee refunds and are not paying any rewards to relayers;
- [x] add required pallets to Bulletin Chain (https://github.com/svyatonik/polkadot-bulletin-chain/tree/add-bridge-pallets):
   - [x] add XCM support to Bulletin Chain (hopefully someone from XCM team could help with that);
   - [x] ~decide whether we want to use utility pallet there~;
   - [x] make sure that we only accept bridge transactions from whitelisted relayers;
   - [x] do not register any rewards at Bulletin Chain, because tokens have no economic value there;
- [x] add bridge support to `substrate-relay`;
- [x] prepare something similar to Branislav setup (zombienet + binaries + document) to launch Polkadot + Polkadot Bridge Hub + Bulletin Chain (and another system parachain later) locally.
- [x] send some test message directly from Polkadot BH to Bulletin Chain (unless other Polkadot parachain is ready).

Follow up tasks: make actual PRs to Polkadot.BH once it is deployed.

A list of live unresolved problems:
- [x] we need to know real dispatch weight of the message. Bulletin chain uses immediate dispatch, so we need to decode the message (and calls) and use XCM weigher for estimating dispatch weight for message delivery transaction (https://github.com/zdave-parity/polkadot-bulletin-chain/pull/33).
- [x] rename Kawabunga to People Chain (see https://github.com/paritytech/polkadot-sdk/pull/2281)
- [x] add Rococo Bridge Hub <> Rococo Bulletin bridge (Rococo Bulletin chain will be deployed and will be 1:1 copy of Polkadot Bulletin)

**Comment by svyatonik** [comment]
Rococo <> RococoBulletin bridge may be tested locally (until centralized deployment) with:
- https://github.com/paritytech/polkadot-sdk/tree/sv-rococo-bulletin-bridge
- https://github.com/paritytech/parity-bridges-common/pull/2724
- https://github.com/svyatonik/polkadot-bulletin-chain/tree/add-bridge-pallets

Instructions: https://github.com/paritytech/polkadot-sdk/blob/sv-rococo-bulletin-bridge/cumulus/parachains/runtimes/bridge-hubs/README-bulletin.md

**Comment by bkontur** [comment]
hint for me: just search TODOs for `https://github.com/paritytech/parity-bridges-common/issues/2547` in the code

**Comment by bkontur** [comment]
closing this, we have already in-progress PeoplePolkadot<>Bulletin PRs
