### ISSUE TITLE
Add Rococo <> Westend asset bridging support

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#2602]
## Summary
BridgeHubWestend is alive but runs `bridge-hub-kusama-runtime` which will be moved soon to the `polkadot-fellows` repo.
We need to deploy on Westend a BridgeHubWestend testnet system parachain but we dont have now dedicated BridgeHubWestend runtime/code.

## Solution
No need to duplicate and create new runtime. We have already `bridge-hub-rococo-runtime` which has [**flavor** feature](https://github.com/paritytech/polkadot-sdk/pull/1215/files#diff-f5e5608adb7096db0c665bb20e5298c113904c48b16633684a7cad72d95b4962R105-R111) which is used also for BridgeHubWococo.
So the simplest solution is to:
- ~~add flavor for Westend~~ add new runtime `bridge-hub-westend-runtime`
- add bridging pallet instances for Rococo<->Westend
- add relayer code for Rococo<->Westend

This issue depends on this PR to be merged: https://github.com/paritytech/polkadot-sdk/pull/1215.

## TODO

- [x] add Westend flavor to BridgeHubRococo
- [x] add bridging assets stuff to AssetHubWestend <> AssetHubRococo
- [x] add relay support for AssetHubWestend <> AssetHubRococo
- [ ] ~~redeploy BridgeHubWestend with `bridge-hub-rococo-runtime`~~ part of https://github.com/paritytech/polkadot-sdk/issues/1988

**Comment by bkontur** [comment]
- [ ] init bridge Rococo -> Westend

#### Init bridge: Rococo -> Wococo

1. Generate `initialize` init-bridge call as `hex-encoded-data`:

```
# Rococo -> Westend
RUST_LOG=bridge=info \
	./target/release/substrate-relay init-bridge rococo-to-bridge-hub-westend \
	--source-host rococo-rpc.polkadot.io \
	--source-port 443 \
	--source-secure \
	--target-host westend-bridge-hub-rpc.polkadot.io \
	--target-port 443 \
	--target-secure \
	--target-signer //Bob \
	--dry-run
	
...

2022-12-02 09:08:38 +00 INFO bridge Initialize bridge call encoded as hex string: "TODO: data"
```

2. Check `hex-encoded-data` here: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-bridge-hub-rpc.polkadot.io#/extrinsics/decode

3. Simulate governance as submit extrinsic `XCM::Transact` with `hex-encoded-data` for `para_id=1002` from **Westend relay node**

**Comment by bkontur** [comment]
- [ ] init bridge Westend -> Rococo

#### Init bridge: Westend -> Rococo

1. Generate `initialize` init-bridge call as `hex-encoded-data`:

```
# Westend -> Rococo
RUST_LOG=bridge=info \
	./target/release/substrate-relay init-bridge westend-to-bridge-hub-rococo \
	--source-host westend-rpc.polkadot.io \
	--source-port 443 \
	--source-secure \
	--target-host rococo-bridge-hub-rpc.polkadot.io \
	--target-port 443 \
	--target-secure \
	--target-signer //Bob \
	--dry-run
	
...

2022-12-02 09:08:38 +00 INFO bridge Initialize bridge call encoded as hex string: "TODO: data"
```

2. Check `hex-encoded-data` here: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-bridge-hub-rpc.polkadot.io#/extrinsics/decode

3. Simulate governance as submit extrinsic `XCM::Transact` with `hex-encoded-data` for `para_id=1013` from **Rococo relay node**

**Comment by bkontur** [comment]
[ ] `foreignAssets.forceSetMetadata` -  sudo call on Rococo for - `force_set_metadata`

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x3513020109041c57657374656e640c574e440c00

**Comment by bkontur** [comment]
- [ ] `foreignAssets.forceSetMetadata` -  sudo call on AssetHubWestend  for - `force_set_metadata`

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x35130201090518526f636f636f0c524f430c00

**Comment by bkontur** [comment]
- [x] `forceXcmVersion` on AssetHubRococo for BridgeHubRococo

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x1f04010100d50f03000000

**Comment by bkontur** [comment]
- [X]  `forceXcmVersion` on AssetHubWestend for BridgeHubWestend

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x1f04010100a90f03000000

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-rpc.polkadot.io#/extrinsics/decode/0x1500630003000100a10f03082f0000060203b08d1b4201102c1f04010100a90f03000000

**Comment by bkontur** [comment]
- [ ] `forceDefaultXcmVersion` on BridgeHubWestend

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-rpc.polkadot.io#/extrinsics/decode/0x1500630001000100a90f03082f0000060203086cbd4105101c1f050103000000

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-bridge-hub-rpc.polkadot.io#/extrinsics/decode/0x1f050103000000

(causing RoutingError, because was 2)

**Comment by bkontur** [comment]
- [ ] `forceXcmVersion` on BridgeHubWestend for AssetHubWestend

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-rpc.polkadot.io#/extrinsics/decode/0x1500630003000100a90f03082f00000602034898234201102c1f04010100a10f03000000

**Comment by bkontur** [comment]
[x]  `forceXcmVersion` on AssetHubRococo for AssetHubWestend

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/extrinsics/decode/0xff00630003000100a10f03082f0000060242cd51410110341f040202090400a10f03000000

**Comment by bkontur** [comment]
- [ ] `forceXcmVersion` on BridgeHubRococo for BridgeHubWestend

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/extrinsics/decode/0xff00630003000100d50f03082f0000060242cd51410110341f040202090400a90f03000000

**Comment by bkontur** [comment]
- [ ] `forceXcmVersion` on AssetHubWestend for AssetHubRococo

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-rpc.polkadot.io#/extrinsics/decode/0x1500630003000100a10f03082f00000602829c6b310110341f040202090500a10f03000000

**Comment by bkontur** [comment]
- [ ] `forceXcmVersion` on BridgeHubWestend for BridgeHubRococo

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-rpc.polkadot.io#/extrinsics/decode/0x1500630003000100a90f03082f00000602829c6b310110341f040202090500d50f03000000
