### ISSUE TITLE
Make sure we backported and released all relevant patches from 1.7.0 untill 1.11.0

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#2994]
- [ ] xcm-emulator https://github.com/paritytech/polkadot-sdk/issues/4428
- [ ] Clara's https://github.com/paritytech/polkadot-sdk/pull/4478
- [ ] backport pallet-xcm::transfer_assets_using_type_and_then() (#3695) (#4462)
- [ ] Slava's fixed GrandpaConsensusLogReader::find_scheduled_change (#4209)
- [ ] other?s

**Comment by bkontur** [comment]
(collecting info for Morgan)

Release patch :

1.7.0
- snowbridge-pallet-ethereum-client

1.8.0
- snowbridge-pallet-ethereum-client

1.9.0
- snowbridge-pallet-ethereum-client

1.10.0
- snowbridge-pallet-ethereum-client

1.11.0
- snowbridge-pallet-ethereum-client

**Comment by bkontur** [comment]
- [ ] check also Cisco's `Add `claim_assets` extrinsic to `pallet-xcm` (#3403) (#3539)`

**Comment by claravanstaden** [comment]
- [] Need this PR merged and backported too: https://github.com/paritytech/polkadot-sdk/pull/4501

**Comment by acatangiu** [comment]
We should get the snowfork 1.7.0 patches published first with high priority to get them included in https://github.com/polkadot-fellows/runtimes/issues/288

Then we can do [rest of these](https://github.com/paritytech/parity-bridges-common/issues/2994#issuecomment-2117123080).

**Comment by bkontur** [comment]
- [ ] check HRMP stuff: https://github.com/paritytech/polkadot-sdk/pull/3721 and https://github.com/paritytech/polkadot-sdk/pull/4332

**Comment by ggwpez** [comment]
https://github.com/paritytech/polkadot-sdk/pull/4398 as well...
